### PR TITLE
Allow network links to also be machines

### PR DESCRIPTION
**Pull request by FrederoxDev**
Allows network links to also be machines

### CODE REVIEW

**Comment by FrederoxDev** [comment]
Weirdly pulling in your changes has completely broken a couple machines in my pack and now low priority storages don't function, imma have to debug what you changed before I think this should be merged.

**Comment by FrederoxDev** [comment]
```
      // return unused storage to generators
      // for (let i = 0; i < distributionData.queueItems.length; i++) {
      //   const sendData = distributionData.queueItems[i];

      //   const machine = sendData.block;
      //   const budgetAllocation = Math.floor(
      //     budget / (distributionData.queueItems.length - i),
      //   );

      //   const machineDef = InternalRegisteredMachine.forceGetInternal(
      //     machine.typeId,
      //   );

      //   const newAmount = Math.min(
      //     budgetAllocation,
      //     machineDef.maxStorage,
      //     sendData.amount,
      //   );

      //   // finally give the machine its allocated share
      //   budget -= newAmount;
      //   setMachineStorage(machine, type, newAmount);
      //   if (budget <= 0) break;
      //   yield;
      // }
      ```

Instead just mark these generators as low priority consumers, this is already a feature in the API

**Comment by Fluffyalien1422** [comment]
> Alternative solution: Instead just mark these generators as low priority consumers since this has the same effect without breaking changes?

Returning unused storage to the generators is the intended behavior (#66) and is currently the behavior in the [latest release](https://github.com/Fluffyalien1422/bedrock-energistics-core/releases/tag/v0.4.0), removing it would be a breaking change.

**Comment by Fluffyalien1422** [comment]
> This section of code seems to be causing my issues, and I can't really work out why it is because it runs after low priority consumers, but it still somehow prevents low priority consumers from receiving? Maybe you can provide some insight into that?

I will look into it

**Comment by Fluffyalien1422** [comment]
By the way, this PR has no description. Can you please provide one?

**Comment by FrederoxDev** [comment]
done, and reverted commenting out the buggy section of code, will fix for my own use case in a later PR.

**Review by Fluffyalien1422 — APPROVED** [review]

**Pull request merged**
